services:
  backend:
    container_name: media_server_be
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "15020:5000"
    env_file: ./backend/.env
    command: sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0:5000 run:app"
    volumes:
      - edited_images:/root/media-server-edited
      - ${MEDIA_PATH:-/media}:/media:ro
      - /home/pritam/media_server_files:/media_files
    networks:
      - default-network
    user: "${UID}:${GID}"
    dns:
      - 172.17.0.1

  worker-import:
    container_name: media_server_w_import
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./backend/.env
    command: sh -c "celery -A app.tasks.celery worker -Q $CELERY_QUEUE_IMPORT -l info --concurrency=1"
    volumes:
      - ${MEDIA_PATH:-/media}:/media:ro
      - /home/pritam/media_server_files:/media_files
    networks:
      - default-network
    dns:
      - 172.17.0.1

  worker-metadata:
    container_name: media_server_w_metadata
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./backend/.env
    command: sh -c "celery -A app.tasks.celery worker -Q $CELERY_QUEUE_METADATA -l info --concurrency=1"
    volumes:
      - ${MEDIA_PATH:-/media}:/media:ro
      - /home/pritam/media_server_files:/media_files
    networks:
      - default-network
    dns:
      - 172.17.0.1

  worker-ai:
    container_name: media_server_w_ai
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./backend/.env
    command: sh -c "celery -A app.tasks.celery worker -Q $CELERY_QUEUE_AI -l info --concurrency=2"
    volumes:
      - ${MEDIA_PATH:-/media}:/media:ro
      - /home/pritam/media_server_files:/media_files
    networks:
      - default-network
    dns:
      - 172.17.0.1

  worker-thumbnail:
    container_name: media_server_w_thumb
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./backend/.env
    command: sh -c "celery -A app.tasks.celery worker -Q $CELERY_QUEUE_THUMBNAIL -l info --concurrency=1"
    volumes:
      - ${MEDIA_PATH:-/media}:/media:ro
      - /home/pritam/media_server_files:/media_files
    networks:
      - default-network
    dns:
      - 172.17.0.1

  frontend:
    container_name: media_server_fe
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "18000:80"
    networks:
      - default-network
    dns:
      - 172.17.0.1

volumes:
  edited_images:

networks:
  default-network:
    external: true
    name: default-network
