"""initial_v2

Revision ID: 403e10a21f62
Revises: 
Create Date: 2026-06-25 13:25:39.056612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403e10a21f62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('mime_groups', sa.JSON(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'path')
    )
    op.create_table('imported_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['imported_directories.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'file_path')
    )
    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('metadata_status', sa.Text(), nullable=False),
    sa.Column('exif', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_words', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('dhash', sa.String(length=16), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('thumbnail_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_metadata_file_hash'), ['file_hash'], unique=False)

    op.create_table('dhash_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('band_index', sa.Integer(), nullable=False),
    sa.Column('band_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dhash_bands', schema=None) as batch_op:
        batch_op.create_index('ix_dhash_band_lookup', ['band_index', 'band_value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dhash_bands', schema=None) as batch_op:
        batch_op.drop_index('ix_dhash_band_lookup')

    op.drop_table('dhash_bands')
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_metadata_file_hash'))

    op.drop_table('file_metadata')
    op.drop_table('imported_files')
    op.drop_table('imported_directories')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
