"""add nickname to imported_files

Revision ID: 8f45fa6bc439
Revises: 403e10a21f62
Create Date: 2026-06-25 23:56:30.717235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f45fa6bc439'
down_revision = '403e10a21f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported_files', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
