"""what changed

Revision ID: b3e75c22743a
Revises: 403e10a21f62
Create Date: 2026-06-25 13:28:10.794440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e75c22743a'
down_revision = '403e10a21f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('dhash', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_file_metadata_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_metadata_file_hash'))
        batch_op.drop_column('dhash')
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
