"""add filter_presets

Revision ID: d78f7404202d
Revises: 9f3d765a153a
Create Date: 2026-06-27 16:39:07.424603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78f7404202d'
down_revision = '9f3d765a153a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('avg_encoding', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_faces',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('encoding', sa.JSON(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('face_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detected_faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_faces_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_faces_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_faces_person_id'))
        batch_op.drop_index(batch_op.f('ix_detected_faces_file_id'))

    op.drop_table('detected_faces')
    op.drop_table('persons')
    # ### end Alembic commands ###
